#!/usr/bin/env python3
"""
PYthon的跑马灯显示效果，需要将数组的元素循环的向左移动，实现显示时的动态效果
"""
import time
array=["A","B","C","D"]
i=1

print(array)

while True:
    m=array[0]
    #将第下标为i的元素赋值给i-1的元素，一直循环，然后将第一个元素赋值给最后一个元素
    while i<len(array):
        array[i-1]=array[i]
        i+=1

    array[i-1]=m
    print(array)
    i=1
    time.sleep(2)
    
    
#以上的程序的输出：
#['A', 'B', 'C', 'D']
#['B', 'C', 'D', 'A']
#['C', 'D', 'A', 'B']
#['D', 'A', 'B', 'C']
#['A', 'B', 'C', 'D']
#['B', 'C', 'D', 'A']
#['C', 'D', 'A', 'B']
#['D', 'A', 'B', 'C']
#.........
#
#
 
 
 #完整的实现
 
 #!/usr/bin/env python3

import time

array=["I"," ","love"," ","you"," "]

def pl(l):
    print("".join(l),end="\r",flush=True)

i=1
pl(array)

while True:
    m=array[0]
    while i<len(array):
        array[i-1]=array[i]
        i+=1

    array[i-1]=m
    pl(array)
    i=1
    time.sleep(0.5)
